# Generated by Django 5.1.1 on 2024-11-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2')], max_length=2),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='level',
            field=models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2')], max_length=2),
        ),
    ]
