# Generated by Django 5.1.1 on 2024-12-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_question_level_alter_testresult_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_a',
            field=models.TextField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_b',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_c',
            field=models.TextField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_d',
            field=models.TextField(blank=True, default=' ', max_length=200),
        ),
    ]
