# Generated by Django 5.1.1 on 2024-12-17 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_studysession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to='my_app.studysession'),
        ),
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together={('course', 'weekday', 'session')},
        ),
    ]
