# Generated by Django 5.1.1 on 2024-11-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_student_has_taken_test_user_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='start_date',
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
