# Generated by Django 5.1.1 on 2024-12-17 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_courseschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'ordering': ['weekday']},
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='start_time',
        ),
    ]
