# Generated by Django 5.1.1 on 2024-11-10 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_student_join_date_remove_teacher_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
