# Generated by Django 5.1.4 on 2025-01-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage'), ('old_student', 'Old Student Discount')], default='percent', max_length=20),
        ),
    ]
