# Generated by Django 5.1.4 on 2024-12-23 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_courseschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('course', 'student', 'date')},
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='discount program name', max_length=200)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (amount or %)', max_digits=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Discount Start Date')),
                ('end_date', models.DateField(help_text='Discount End Date')),
                ('courses', models.ManyToManyField(related_name='discounts', to='my_app.course')),
            ],
        ),
    ]
