# Generated by Django 5.1.4 on 2025-01-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_discount_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='for_old_students_only',
            field=models.BooleanField(default=False, help_text='Apply only for old students'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage')], default='percent', max_length=20),
        ),
    ]
